### ISSUE TITLE
To-Do Prompting! ✅

### ISSUE THREAD

**Issue by saumyacoder1709** [opencodeiiita/Techtonic#93]
**This issue is competitive, and only the best PR will be merged.**  

The other **Top 3 PRs** will receive **partial points**, so bring your A-game!  

---

**Problem Statement:**  
Create a **To-Do List webpage** using only **HTML, CSS, and JavaScript** (**No APIs or Libraries allowed**).  

This task encourages the use of AI prompts to find solutions, so you must outdo your peers! 😄  
Make your webpage stand out by adding unique features like random hardcoded quotes, sound effects, or any other creative ideas related to the To-Do list.  

**No APIs are allowed.**  

The best PR will be judged based on **attractive features**, **design**, and **content**.  
Think and go crazy with it!!! 
---

**Submission Guidelines:**  
- **Host your webpage** on GitHub Pages.  
- Learn how to do it [here](https://www.geeksforgeeks.org/how-to-host-a-website-on-github-for-free/) or prompt it too 🙄.  
- Submit the link to your **webpage** and the **github repository** containing the HTML, CSS, and/or JavaScript code in a **rollno.txt** file, pushed into the branch named **"Chat"**.  
- **Deadline:** December 22, 04:00 pm. No PRs will be accepted after this time. 

---

The final evaluation lies with the mentor, and **no discussions** will be allowed on the results. Note that if your webpage resembles look-alike of your peer's webpage, it will be termed as negative marks in the evaluation criteria. 

---

_- What is the best way to approach this issue??_

**Comment by sahsudhanshu** [comment]
claim

**Comment by saumyacoder1709** [comment]
No need to claim this issue.

**Comment by saumyacoder1709** [comment]
The deadline and the point system is updated now! Make sure to check it out.

**Comment by rajdeep13-coder** [comment]
Is this open for all, or just for IIIT-A freshers?

**Comment by saumyacoder1709** [comment]
Just for IIITA freshers.

**Comment by saumyacoder1709** [comment]
The deadline is extended till Dec 22 4pm.
